language: en
#pipeline: "spacy_sklearn"
pipeline: "tensorflow_embedding"
#- name: "nlp_spacy"
#- name: "tokenizer_spacy"
#- name: "intent_entity_featurizer_regex"
#- name: "intent_featurizer_spacy"
#- name: "ner_crf"
#- name: "intent_classifier_sklearn"